name: Build
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  FORCE_COLOR: "1"

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: Package
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        target: ["Ubuntu", "Windows", "macOS"]
        include:
          - target: "Ubuntu"
            platform: "Linux"
            output-format: "system"
            runs-on: "ubuntu-latest"
            pre-command: |
              sudo apt-get update --fix-missing
              sudo apt-get install -y \
                socat libcairo2-dev libgirepository1.0-dev gir1.2-gtk-3.0 \
                libcanberra-gtk3-module build-essential git uuid-dev \
                libblkid-dev libmount-dev
            briefcase-run-prefix: "xvfb-run"
            briefcase-args: "--target ubuntu"

          - target: "Windows"
            output-format: "app"
            runs-on: "windows-latest"

          - target: "macOS"
            output-format: "app"
            runs-on: "macos-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install Briefcase
        run: |
          python -m pip install --upgrade pip
          python -m pip install briefcase

      - name: Setup Environment
        run: ${{ matrix.pre-command }}

      - name: Build App
        run: |
          ${{ matrix.briefcase-run-prefix }} \
          briefcase build \
            ${{ matrix.platform || matrix.target }} \
            ${{ matrix.output-format }} \
            ${{ matrix.briefcase-args }}

      - name: Package App
        run: |
          if [ "${{ matrix.target }}" = "macOS" ]; then
            briefcase package macOS app \
              --update \
              --no-input \
              --log \
              --adhoc-sign \
              -p pkg \
              ${{ matrix.briefcase-args }}

          elif [ "${{ matrix.target }}" = "Windows" ]; then
            briefcase package Windows app \
              --update \
              --no-input \
              --log \
              -p zip \
              ${{ matrix.briefcase-args }}

          else
            briefcase package Linux system \
              --update \
              --no-input \
              --log \
              ${{ matrix.briefcase-args }}

            cd dist
            zip -r BTCZPayOverlay-linux.zip *
          fi

      - name: Upload App (Linux / macOS)
        if: matrix.target != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: BTCZPayOverlay-${{ matrix.target }}
          path: dist
          if-no-files-found: warn

      - name: Upload App (Windows)
        if: matrix.target == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: BTCZPayOverlay
          path: |
            dist/*.zip
          if-no-files-found: warn