name: Build
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  FORCE_COLOR: "1"

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: Package
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        target: ["Ubuntu", "Windows", "macOS"]

        include:
          - target: "Ubuntu"
            platform: "Linux"
            output-format: "system"
            runs-on: "ubuntu-24.04"
            pre-command: |
              sudo apt-get update --fix-missing
              sudo apt-get install -y \
                socat libcairo2-dev libgirepository1.0-dev gir1.2-gtk-3.0 \
                libcanberra-gtk3-module build-essential git uuid-dev \
                libblkid-dev libmount-dev
            briefcase-run-prefix: "xvfb-run"

          - target: "Windows"
            output-format: "app"
            runs-on: "windows-latest"

          - target: "macOS"
            output-format: "app"
            runs-on: "macos-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Briefcase
        run: |
          if [ "${{ matrix.target }}" = "Ubuntu" ]; then
            python3 -m venv .briefcase-venv
            . .briefcase-venv/bin/activate
            python -m pip install --upgrade pip
            python -m pip install briefcase
          else
            python -m pip install --upgrade pip
            python -m pip install briefcase
          fi

      - name: Setup Environment
        run: ${{ matrix.pre-command }}

      - name: Package App
        run: |
          if [ "${{ matrix.target }}" = "Ubuntu" ]; then
            source .briefcase-venv/bin/activate
          fi

          if [ "${{ matrix.target }}" = "macOS" ]; then
            briefcase package macOS app \
              --update \
              --no-input \
              --log \
              --adhoc-sign \
              -p pkg

          elif [ "${{ matrix.target }}" = "Windows" ]; then
            briefcase package Windows app \
              --update \
              --no-input \
              --log \
              -p zip

          else
            ${{ matrix.briefcase-run-prefix }} \
            briefcase package \
              ${{ matrix.platform || matrix.target }} \
              ${{ matrix.output-format }} \
              --update \
              --no-input \
              --log
          fi

      - name: Upload App (Linux / macOS)
        if: matrix.target != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: BTCZPayOverlay-${{ matrix.target }}
          path: dist
          if-no-files-found: warn

      - name: Upload App (Windows)
        if: matrix.target == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: BTCZPayOverlay
          path: |
            dist/*.zip
          if-no-files-found: warn